### ISSUE TITLE
3.0.0 Open Source Umbrella

### ISSUE THREAD

**Issue by jonambas** [SparkPost/matchbox#116]
## Summary
Prepare this codebase for an open source release. Remove or abstract any SparkPost-only resources, components, styles.

## To do

FE-141 -
- [ ] Tests

FE-143 -
- [x] ~~Remove typography dep~~
- [x] Remove EmptyState SVGs
- [x] Fully export MD icons
- [x] Create additional color palettes

FE-147 -
- [ ] Clean up Storybook stories

Others -
- [ ] https://github.com/SparkPost/matchbox/issues/117
- [ ] Button and UnstyledLink prop `Component` should be lowercased to `component`
- [ ] Panel `accent` prop should accept a string for colors
- [ ] Grid and Column props need to be expanded
  - [ ] `first` and `last` props
  - [ ] Consistent margin bottom of `spacing()`
